require('dotenv').config({ override: true });
require('express-async-errors');
const express=require('express');
const path=require('path');
const {marked}=require('marked');
const session=require('express-session');
const PgStore=require('connect-pg-simple')(session);
const db=require('./src/db/db');
const {router:authRouter,requireAuth}=require('./src/routes/auth');
const {fixMojibake}=require('./src/services/textService');
const {ensurePlatformReady}=require('./src/services/platformBootstrap');
const {ensureChecklistReady}=require('./src/services/checklistBootstrap');

const app=express();
const PORT=process.env.PORT||3000;
if(!process.env.SESSION_SECRET)throw new Error('SESSION_SECRET não configurada.');
app.set('trust proxy',1);
app.set('view engine','ejs');
app.set('views',path.join(__dirname,'views'));
app.use(express.urlencoded({extended:true}));
app.use(express.json());
app.use(express.static(path.join(__dirname,'public')));
app.use(session({store:new PgStore({pool:db.pool,tableName:'user_sessions',createTableIfMissing:true}),secret:process.env.SESSION_SECRET,proxy:true,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));
app.use(async(req,res,next)=>{try{await ensurePlatformReady();await ensureChecklistReady();next()}catch(error){next(error)}});
app.get('/api/health',async(req,res)=>{try{await db.ping();res.json({status:'ok',database:'postgresql',intelligence:'calibrated',accessControl:'enabled',adaptiveStudy:'enabled'})}catch{res.status(503).json({status:'error',database:'unavailable'})}});
app.use(async(req,res,next)=>{try{res.locals.markdownToHtml=md=>marked.parse(md||'');res.locals.title='';res.locals.active='';res.locals.t=fixMojibake;res.locals.user=req.session.userId?await db.one('SELECT id,email,name,role,approval_status,access_until FROM users WHERE id=$1',[req.session.userId]):null;next()}catch(e){next(e)}});
app.use(authRouter);
app.use(requireAuth);
app.use((req,res,next)=>{const map={'/':'dashboard','/proxima-prova':'proxima','/previsao-ia':'previsao','/dificuldade':'dificuldade','/questoes-repetidas':'repetidas','/analise':'analise','/plano-estudos':'plano','/questoes':'questoes','/simulados':'simulados','/import':'import','/editais':'editais','/recorrencias':'recorrencias','/estudar-hoje':'hoje','/treino':'treino','/caderno-erros':'erros','/minha-conta':'conta','/admin/usuarios':'admin'};const base='/'+req.path.split('/').filter(Boolean).slice(0,2).join('/');const first='/'+req.path.split('/')[1];res.locals.active=map[req.path]||map[base]||map[first]||'';next()});
app.use('/',require('./src/routes/accountAdmin'));
app.use('/',require('./src/routes/main'));
app.use('/import',require('./src/routes/import'));
app.use('/simulados',require('./src/routes/simulados'));
app.use('/',require('./src/routes/intelligence'));
app.use('/',require('./src/routes/prediction'));
app.use((req,res)=>res.status(404).render('error',{message:'Página não encontrada.'}));
app.use((error,req,res,next)=>{console.error(error);if(res.headersSent)return next(error);res.status(500).render('error',{message:error.message||'Não foi possível concluir a operação.'})});
if(require.main===module){const server=app.listen(PORT,()=>console.log(`ESFCEx Informática Prep rodando em http://localhost:${PORT}`));server.on('error',e=>{if(e.code==='EADDRINUSE'){console.error(`A porta ${PORT} ja esta em uso.`);process.exit(1)}throw e})}
module.exports=app;
