const express=require('express');
const router=express.Router();
const db=require('../db/db');
const {DAY_LABELS}=require('../services/scheduleEngine');
const {canonicalDiscipline,canonicalTopic}=require('../services/intelligenceEngine');
const {getStudyTargets,attachProgress}=require('../services/analysisEngine');
const {getMicrotopics,getResource,getAdaptiveSignals,getPerformanceByDiscipline,getHistory,ensureChecklistForBlocks}=require('../services/adaptivePlanEngine');
const {getOrCreateCurrentWeek,generateNextWeek,markCurrentWeekCompleted,getWeekCompletion,dateMapForWeek,getWeekBounds,saoPauloNow,isoDate,getWeekPlan}=require('../services/weeklyPlanSnapshot');
function planKey(discipline,topic){return `${canonicalDiscipline(discipline).toLowerCase()}||${canonicalTopic(topic).toLowerCase()}`;}
async function getLatestEditalTopics(userId){const edital=await db.one('SELECT id,ano,banca,cargo FROM editais WHERE user_id=$1 ORDER BY ano DESC,created_at DESC LIMIT 1',[userId]);if(!edital)return{edital:null,topics:[]};const topics=await db.query('SELECT * FROM edital_topics WHERE edital_id=$1 ORDER BY discipline,topic,subtopic',[edital.id]);const progressRows=await db.query('SELECT discipline,topic,progress,notes FROM study_progress WHERE user_id=$1',[userId]);const progressMap=new Map(progressRows.map(row=>[planKey(row.discipline,row.topic),row]));return{edital,topics:topics.map(item=>{const progress=progressMap.get(planKey(item.discipline,item.topic));return{...item,progress:Number(progress?.progress||0),progress_notes:progress?.notes||null}})}}
async function getPlanInputs(userId){const preferences=await db.one('SELECT days,hours_per_day FROM study_plan_preferences WHERE user_id=$1',[userId]);const selectedDays=preferences&&Array.isArray(preferences.days)?preferences.days:['mon','tue','wed','thu','fri','sat'];const hoursPerDay=preferences?Number(preferences.hours_per_day):2;const studyTargets=await attachProgress(await getStudyTargets(60,userId),userId);const{edital,topics:editalTopics}=await getLatestEditalTopics(userId);const adaptiveSignals=await getAdaptiveSignals(userId);return{selectedDays,hoursPerDay,studyTargets,edital,editalTopics,adaptiveSignals};}
router.get('/plano-estudos',async(req,res)=>{const userId=req.session.userId;const items=await db.query('SELECT * FROM study_plan WHERE user_id=$1 ORDER BY priority_score DESC',[userId]);const input=await getPlanInputs(userId);const{plan}=await getOrCreateCurrentWeek({userId,targets:input.studyTargets,editalTopics:input.editalTopics,days:input.selectedDays,hoursPerDay:input.hoursPerDay,adaptiveSignals:input.adaptiveSignals});const weeklySchedule=plan.schedule;const dates=dateMapForWeek(String(plan.week_start).slice(0,10));await ensureChecklistForBlocks(userId,weeklySchedule.blocks,dates);const checklist=await db.query(`SELECT * FROM study_checklist_entries WHERE user_id=$1 AND study_date BETWEEN $2::date AND $3::date ORDER BY study_date,id`,[userId,String(plan.week_start).slice(0,10),String(plan.week_end).slice(0,10)]);const todayIso=isoDate(saoPauloNow());const todayBlocks=weeklySchedule.blocks.filter(block=>dates[block.day]===todayIso);const todayChecklist=checklist.filter(item=>String(item.study_date).slice(0,10)===todayIso);const performance=await getPerformanceByDiscipline(userId);const history=await getHistory(userId);const microMap={};weeklySchedule.queue.slice(0,40).forEach(item=>{microMap[planKey(item.discipline,item.topic)]=getMicrotopics(item.discipline,item.topic).map(micro=>({...getResource(item.discipline,item.topic,micro),microtopic:micro}))});const weekCompletion=await getWeekCompletion(userId,String(plan.week_start).slice(0,10),String(plan.week_end).slice(0,10));const nextBounds=getWeekBounds(1);const nextPlan=await getWeekPlan(userId,nextBounds.weekStart);res.render('study_plan',{items,studyTargets:input.studyTargets,weeklySchedule,todayBlocks,todayChecklist,checklist,performance,history,microMap,dates,edital:input.edital,editalTopics:input.editalTopics,dayLabels:DAY_LABELS,selectedDays:plan.config?.days||input.selectedDays,hoursPerDay:Number(plan.config?.hoursPerDay||input.hoursPerDay),querySaved:req.query.saved||'',queryError:req.query.error||'',weekPlan:plan,weekCompletion,nextPlan})});
router.post('/plano-estudos/dia/concluir',async(req,res)=>{const userId=req.session.userId;const today=isoDate(saoPauloNow());await db.query(`UPDATE study_checklist_entries SET completed=TRUE,completed_at=COALESCE(completed_at,CURRENT_TIMESTAMP) WHERE user_id=$1 AND study_date=$2::date`,[userId,today]);res.redirect('/plano-estudos?saved=day')});
router.post('/plano-estudos/agenda/salvar',async(req,res)=>{const requestedDays=Array.isArray(req.body.days)?req.body.days:(req.body.days?[req.body.days]:[]);const selectedDays=requestedDays.filter(day=>DAY_LABELS[day]);const hoursPerDay=Math.max(.5,Math.min(12,Number(req.body.hoursPerDay)||2));await db.query(`INSERT INTO study_plan_preferences(user_id,days,hours_per_day,updated_at) VALUES($1,$2::jsonb,$3,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET days=excluded.days,hours_per_day=excluded.hours_per_day,updated_at=CURRENT_TIMESTAMP`,[req.session.userId,JSON.stringify(selectedDays),hoursPerDay]);res.redirect('/plano-estudos?saved=agenda-next')});
router.post('/plano-estudos/semana/concluir',async(req,res)=>{const userId=req.session.userId;const current=getWeekBounds(0);const currentPlan=await getWeekPlan(userId,current.weekStart);if(currentPlan?.status==='completed')return res.redirect('/plano-estudos?saved=next');const completion=await getWeekCompletion(userId,current.weekStart,current.weekEnd);if(!completion.complete)return res.redirect('/plano-estudos?error=week-incomplete');const input=await getPlanInputs(userId);const nextPlan=await generateNextWeek({userId,targets:input.studyTargets,editalTopics:input.editalTopics,days:input.selectedDays,hoursPerDay:input.hoursPerDay,adaptiveSignals:input.adaptiveSignals,metrics:{previousWeekCompletion:completion.percent,generatedAfterChecklist:true}});await markCurrentWeekCompleted(userId);const nextDates=dateMapForWeek(String(nextPlan.week_start).slice(0,10));await ensureChecklistForBlocks(userId,nextPlan.schedule.blocks,nextDates);res.redirect('/plano-estudos?saved=next')});
router.post('/plano-estudos/gerar',async(req,res)=>res.redirect('/plano-estudos?error=use-next-week'));
module.exports=router;