const { GoogleGenerativeAI } = require('@google/generative-ai');
const DEFAULT_MODEL='gemini-3.6-flash';
const configuredModel=process.env.GEMINI_MODEL||DEFAULT_MODEL;
const MODEL=['gemini-2.5-flash','models/gemini-2.5-flash'].includes(configuredModel)?DEFAULT_MODEL:configuredModel;
const FALLBACK_MODELS=(process.env.GEMINI_FALLBACK_MODELS||'gemini-3.5-flash,gemini-3.5-flash-lite').split(',').map(x=>x.trim()).filter(Boolean);
const PDF_CHUNK_SIZE=Number(process.env.PDF_AI_CHUNK_SIZE)||18000, PDF_CHUNK_OVERLAP=Number(process.env.PDF_AI_CHUNK_OVERLAP)||1800;
function getClient(){if(!process.env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY não configurada.');return new GoogleGenerativeAI(process.env.GEMINI_API_KEY)}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function askGemini({system,prompt,maxTokens=4000,json=false}){const genAI=getClient();let last;for(const name of [MODEL,...FALLBACK_MODELS.filter(x=>x!==MODEL)]){const model=genAI.getGenerativeModel({model:name,systemInstruction:system,generationConfig:{maxOutputTokens:maxTokens,...(json?{responseMimeType:'application/json'}:{})}});for(let a=0;a<3;a++){try{return (await model.generateContent(prompt)).response.text()}catch(e){last=e;if(!/(429|500|502|503|504|Unavailable|demand)/i.test(String(e.message||e)))throw e;await sleep(Math.min(1000*2**a,5000))}}}throw last}
function extractJson(text){const c=String(text||'').replace(/```json/gi,'').replace(/```/g,'').trim();const starts=[c.indexOf('['),c.indexOf('{')].filter(x=>x>=0);const start=Math.min(...starts),end=Math.max(c.lastIndexOf(']'),c.lastIndexOf('}'));if(!Number.isFinite(start)||end<start)throw new Error('A IA não retornou JSON válido.');return JSON.parse(c.slice(start,end+1))}
function splitPdfText(rawText,chunkSize=PDF_CHUNK_SIZE,overlap=PDF_CHUNK_OVERLAP){const text=String(rawText||'').replace(/\r\n/g,'\n').trim();if(!text)return[];if(text.length<=chunkSize)return[text];const out=[];let s=0;while(s<text.length){let e=Math.min(s+chunkSize,text.length);const b=text.lastIndexOf('\n',e);if(e<text.length&&b>s+chunkSize*.7)e=b;out.push(text.slice(s,e));if(e>=text.length)break;s=Math.max(s+1,e-overlap)}return out}
function mergeQuestionBatches(batches){const m=new Map();for(const q of batches.flat()){if(!q)continue;const key=Number(q.number)>0?`n:${q.number}`:`s:${String(q.statement||'').toLowerCase().replace(/\s+/g,' ').slice(0,180)}`;if(!m.has(key)||JSON.stringify(q).length>JSON.stringify(m.get(key)).length)m.set(key,q)}return[...m.values()].sort((a,b)=>(Number(a.number)||999)-(Number(b.number)||999))}
function normalizeExpectedQuestions(q,n){const e=Number(n);return mergeQuestionBatches([q]).filter(x=>!Number.isInteger(e)||(Number(x.number)>=1&&Number(x.number)<=e))}
function getMissingQuestionNumbers(q,n){const f=new Set(q.map(x=>Number(x.number)));return Array.from({length:n},(_,i)=>i+1).filter(x=>!f.has(x))}
async function parsePdfToQuestions(rawText,meta={}){const system=`Extraia questões de concurso brasileiro. Responda APENAS JSON. Cada item: number, discipline, topic, statement, alt_a, alt_b, alt_c, alt_d, alt_e, correct_letter, style_notes. Preserve o enunciado e alternativas; não invente conteúdo.`;const chunks=splitPdfText(rawText);if(!chunks.length)throw new Error('PDF sem texto extraível.');const batches=[];for(let i=0;i<chunks.length;i++){const text=await askGemini({system,prompt:`Banca ${meta.banca||'VUNESP'}, ESFCEx, ${meta.cargo||'Informática'}, ${meta.ano||''}. Extraia todas as questões completas deste trecho ${i+1}/${chunks.length}:\n${chunks[i]}`,maxTokens:16000,json:true});batches.push(extractJson(text))}const expected=Number(meta.expectedQuestions);let questions=normalizeExpectedQuestions(mergeQuestionBatches(batches),expected);if(Number.isInteger(expected)&&expected>0){const missing=getMissingQuestionNumbers(questions,expected);if(missing.length||questions.length!==expected)throw new Error(`Importação incompleta: ${questions.length}/${expected}. Ausentes: ${missing.join(', ')}.`)}return questions}
async function parseEdital(rawText,meta={}){const system=`Você é um auditor de edital de concurso. Extraia SOMENTE conteúdos programáticos explicitamente presentes no texto. Responda apenas JSON no formato {summary,topics:[{discipline,topic,subtopic,reference_text,weight}]}. weight deve ser 1 para item comum, 1.5 para item enfatizado/repetido e 2 para requisito explicitamente central. Não invente conteúdo.`;return extractJson(await askGemini({system,prompt:`Edital ESFCEx ${meta.ano||''}, cargo ${meta.cargo||'Informática'}, banca ${meta.banca||'VUNESP'}. Extraia a matriz objetiva de estudo:\n${String(rawText||'').slice(0,150000)}`,maxTokens:12000,json:true}))}
async function generatePatternReport(statsSummary){const system=`Analise historicamente provas VUNESP/ESFCEx. Produza relatório Markdown objetivo e um bloco JSON predicted_weights_2027. Diferencie evidência histórica de hipótese; nunca prometa prever questões literais.`;const text=await askGemini({system,prompt:JSON.stringify(statsSummary),maxTokens:5000});let weights=[];try{const m=text.match(/```json([\s\S]*?)```/);if(m){const p=JSON.parse(m[1]);weights=p.predicted_weights_2027||p}}catch{}return{content_md:text,weights}}
async function generateStudyPlan({weights,performance,report=null}){const system=`Gere APENAS array JSON de plano ESFCEx: discipline,topic,priority_score,rationale,study_notes. Use somente assuntos fornecidos e explique prioridade por evidência e desempenho.`;return extractJson(await askGemini({system,prompt:JSON.stringify({weights,performance,report}),maxTokens:8000,json:true}))}
async function generatePracticeQuestions({discipline,topic,count=5,examples=[]}){const system=`Você atua como elaborador de questões inéditas de treino no estilo VUNESP/ESFCEx. Imite características observáveis dos exemplos (profundidade, tipo de comando, distratores e pegadinhas), mas NÃO copie frases, números, alternativas ou enunciados. Responda apenas array JSON com discipline,topic,statement,alt_a,alt_b,alt_c,alt_d,alt_e,correct_letter,explanation.`;return extractJson(await askGemini({system,prompt:`Disciplina: ${discipline}; assunto: ${topic}; quantidade: ${count}. Exemplos históricos para calibrar estilo:\n${JSON.stringify(examples.slice(0,8))}`,maxTokens:10000,json:true}))}
async function explainQuestion(question){return askGemini({system:'Explique questões de concurso com precisão e objetividade.',prompt:`${question.statement}\nA) ${question.alt_a}\nB) ${question.alt_b}\nC) ${question.alt_c}\nD) ${question.alt_d}\nE) ${question.alt_e||''}\nGabarito: ${question.correct_letter}`,maxTokens:1400})}
module.exports={parsePdfToQuestions,splitPdfText,mergeQuestionBatches,normalizeExpectedQuestions,getMissingQuestionNumbers,parseEdital,generatePatternReport,generateStudyPlan,generatePracticeQuestions,explainQuestion};
