const { canonicalDiscipline, canonicalTopic } = require('./intelligenceEngine');
const DAY_LABELS={mon:'Segunda',tue:'Terça',wed:'Quarta',thu:'Quinta',fri:'Sexta',sat:'Sábado',sun:'Domingo'};
const STUDY_MINUTES_PER_DISCIPLINE=120;
const QUESTION_MINUTES_PER_DISCIPLINE=60;
const DISCIPLINE_BLOCK_MINUTES=180;
const DAY_PLAN={
  mon:[['programacao','linguagem c','c++','python','java','php','algoritmos','estruturas de dados','orientacao a objetos','openmp','mpi'],['portugues','lingua portuguesa']],
  tue:[['redes','tcp','ip','dns','sub-redes'],['historia','geografia']],
  wed:[['sistemas operacionais','linux','shell','processos','memoria virtual'],['banco de dados','sql','transacoes','concorrencia']],
  thu:[['programacao','linguagem c','c++','python','java','php','algoritmos','estruturas de dados','orientacao a objetos','openmp','mpi'],['portugues','lingua portuguesa']],
  fri:[['arquitetura de computadores','arquitetura','sistemas digitais','raid','hierarquia de memoria','cache'],['gerencia de projetos','engenharia de software','pmbok','uml']],
  sat:[['portugues','historia','geografia'],['programacao','redes','sistemas operacionais','banco de dados','arquitetura de computadores','gerencia de projetos','engenharia de software','pmbok','uml']]
};
function normalizeDays(days){const value=Array.isArray(days)?days:(days?[days]:[]);return value.filter(day=>DAY_LABELS[day]);}
function norm(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function topicKey(discipline,topic){return `${norm(canonicalDiscipline(discipline))}||${norm(canonicalTopic(topic))}`;}
function itemMatches(item,aliases=[]){const haystack=norm(`${item?.discipline||''} ${item?.topic||''}`);return aliases.some(alias=>haystack.includes(norm(alias)));}
function signalMap(signals=[]){return new Map(signals.map(s=>[topicKey(s.discipline,s.topic),s]));}
function buildStudyQueue({targets=[],editalTopics=[],adaptiveSignals=[]}){const byKey=new Map(),signals=signalMap(adaptiveSignals);for(const target of targets){const discipline=canonicalDiscipline(target.discipline),topic=canonicalTopic(target.topic),key=topicKey(discipline,topic),signal=signals.get(key);const base=Number(target.score||target.priority_score||50);const adaptiveBoost=signal?Math.round((signal.weakness||0)*.22):0;byKey.set(key,{...target,discipline,topic,sourceType:'historico',priority:Math.min(100,base+adaptiveBoost),editalRequired:false,adaptiveSignal:signal||null});}for(const item of editalTopics){const discipline=canonicalDiscipline(item.discipline),topic=canonicalTopic(item.topic),key=topicKey(discipline,topic),existing=byKey.get(key),signal=signals.get(key);if(existing){existing.editalRequired=true;existing.sourceType='edital+historico';existing.priority=Math.min(100,Math.max(existing.priority,65+Number(item.weight||1)*10)+(signal?Math.round((signal.weakness||0)*.12):0));existing.editalReference=item.reference_text||item.subtopic||null;existing.progress=Math.max(Number(existing.progress||0),Number(item.progress||0));}else{byKey.set(key,{discipline,topic,progress:Number(item.progress||0),score:60+Number(item.weight||1)*10,priority:Math.min(100,60+Number(item.weight||1)*10+(signal?Math.round((signal.weakness||0)*.2):0)),confidence:'EDITAL',sourceType:'edital',editalRequired:true,editalReference:item.reference_text||item.subtopic||null,source:'Conteúdo oficial do edital',sourceUrl:`/treino?discipline=${encodeURIComponent(discipline)}&topic=${encodeURIComponent(topic)}`,adaptiveSignal:signal||null});}}return [...byKey.values()].sort((a,b)=>{const aDone=Number(a.progress||0)>=100?1:0,bDone=Number(b.progress||0)>=100?1:0;if(aDone!==bDone)return aDone-bDone;if(a.editalRequired!==b.editalRequired)return a.editalRequired?-1:1;return Number(b.priority||0)-Number(a.priority||0);});}
function buildDailyTasks(day){if(day==='sat')return ['Revisar erros e pontos fracos do ciclo semanal (120 min)','Resolver bloco de questões/simulado dirigido (60 min)','Registrar erros para recalibrar a próxima semana'];return [`Estudo focado no assunto exato e seus subtópicos cobrados (${STUDY_MINUTES_PER_DISCIPLINE} min)`,`Questões do mesmo assunto (${QUESTION_MINUTES_PER_DISCIPLINE} min)`,'Corrigir erros e registrar o checklist para calibrar a próxima semana'];}
function sortPriority(items,rotationKeys=new Set()){return [...items].sort((a,b)=>{const ar=rotationKeys.has(topicKey(a.discipline,a.topic))?1:0,br=rotationKeys.has(topicKey(b.discipline,b.topic))?1:0;if(ar!==br)return ar-br;if(a.editalRequired!==b.editalRequired)return a.editalRequired?-1:1;return Number(b.priority||0)-Number(a.priority||0);});}
function pickForAliases(pending,aliases,used,rotationKeys){const all=sortPriority(pending.filter(item=>itemMatches(item,aliases)),rotationKeys);const fresh=all.find(item=>!used.has(topicKey(item.discipline,item.topic)));return fresh||all[0]||null;}
function buildWeeklySchedule({targets=[],editalTopics=[],days,hoursPerDay,adaptiveSignals=[],rotationTopics=[]}){const studyDays=normalizeDays(days),requestedHours=Math.max(6,Math.min(12,Number(hoursPerDay)||6)),blocksPerDay=Math.max(2,Math.floor(requestedHours/3)),hours=blocksPerDay*3,queue=buildStudyQueue({targets,editalTopics,adaptiveSignals}),pending=queue.filter(item=>Number(item.progress||0)<100),rotationKeys=new Set(rotationTopics.map(item=>typeof item==='string'?item:topicKey(item.discipline,item.topic))),totalEdital=queue.filter(i=>i.editalRequired).length,editalDone=queue.filter(i=>i.editalRequired&&Number(i.progress||0)>=100).length,editalCoverage=totalEdital?Math.round(editalDone/totalEdital*100):0;if(!studyDays.length||!pending.length)return{studyDays,hoursPerDay:hours,totalWeeklyMinutes:0,blocks:[],summary:[],queue,totalEdital,editalDone,editalCoverage,weeksToCover:0,pendingTopics:pending.length,scheduledTopics:0};const blocks=[],used=new Set();for(const day of studyDays){const slots=DAY_PLAN[day]||[];for(let slot=0;slot<Math.min(blocksPerDay,slots.length);slot++){const aliases=slots[slot]||[];if(!aliases.length)continue;const target=pickForAliases(pending,aliases,used,rotationKeys);if(!target)continue;used.add(topicKey(target.discipline,target.topic));blocks.push({day,dayLabel:DAY_LABELS[day],minutes:DISCIPLINE_BLOCK_MINUTES,studyMinutes:120,questionMinutes:60,discipline:target.discipline,topic:target.topic,score:target.priority||target.score||50,confidence:target.confidence||(target.editalRequired?'EDITAL':'HISTÓRICO'),source:target.source||'Material focado do assunto',sourceUrl:target.sourceUrl||`/treino?discipline=${encodeURIComponent(target.discipline)}&topic=${encodeURIComponent(target.topic)}`,progress:Number(target.progress||0),editalRequired:!!target.editalRequired,editalReference:target.editalReference||null,sourceType:target.sourceType,tasks:buildDailyTasks(day),adaptiveSignal:target.adaptiveSignal||null,planReason:`${DAY_LABELS[day]}: ${target.discipline} · ${target.topic}`});}}const totalWeeklyMinutes=blocks.reduce((sum,b)=>sum+b.minutes,0),summaryMap=new Map();for(const block of blocks){const key=topicKey(block.discipline,block.topic),current=summaryMap.get(key)||{discipline:block.discipline,topic:block.topic,minutes:0,score:block.score,editalRequired:block.editalRequired};current.minutes+=block.minutes;summaryMap.set(key,current);}const capacityPerWeek=Math.max(1,blocks.length);return{studyDays,hoursPerDay:hours,totalWeeklyMinutes,blocks,summary:[...summaryMap.values()].sort((a,b)=>b.minutes-a.minutes),queue,totalEdital,editalDone,editalCoverage,weeksToCover:Math.ceil(pending.length/capacityPerWeek),pendingTopics:pending.length,scheduledTopics:new Set(blocks.map(b=>topicKey(b.discipline,b.topic))).size};}
module.exports={buildWeeklySchedule,buildStudyQueue,DAY_LABELS,DAY_PLAN,topicKey};
