const db=require('../db/db');
const {buildWeeklySchedule,DAY_LABELS}=require('./scheduleEngine');
const PLAN_ALGORITHM_VERSION='2026-08-21-v3';
function saoPauloNow(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const get=type=>Number(parts.find(p=>p.type===type)?.value);return new Date(get('year'),get('month')-1,get('day'),get('hour'),get('minute'),get('second'));}
function normalizeDate(value){if(value instanceof Date)return Number.isNaN(value.getTime())?null:value;if(typeof value==='string'){const match=value.match(/^(\d{4})-(\d{2})-(\d{2})/);if(match){const date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),12,0,0,0);return Number.isNaN(date.getTime())?null:date;}const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed;}return null;}
function isoDate(value){const date=normalizeDate(value);if(!date)return null;const year=date.getFullYear();const month=String(date.getMonth()+1).padStart(2,'0');const day=String(date.getDate()).padStart(2,'0');return `${year}-${month}-${day}`;}
function getWeekBounds(offsetWeeks=0){const now=saoPauloNow();const jsDay=now.getDay();const monday=new Date(now);monday.setHours(12,0,0,0);monday.setDate(now.getDate()-((jsDay+6)%7)+(offsetWeeks*7));const sunday=new Date(monday);sunday.setDate(monday.getDate()+6);return{weekStart:isoDate(monday),weekEnd:isoDate(sunday)};}
function dateMapForWeek(weekStart){const monday=normalizeDate(weekStart);if(!monday)throw new Error(`Data inicial da semana inválida: ${weekStart}`);const map={};Object.keys(DAY_LABELS).forEach((key,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);map[key]=isoDate(d);});return map;}
function parseJson(value,fallback){if(!value)return fallback;if(typeof value==='object')return value;try{return JSON.parse(value)}catch{return fallback}}
async function getWeekPlan(userId,weekStart){const row=await db.one('SELECT * FROM study_week_plans WHERE user_id=$1 AND week_start=$2::date',[userId,weekStart]);if(!row)return null;return{...row,schedule:parseJson(row.schedule_json,{}),config:parseJson(row.config_json,{}),metrics:parseJson(row.metrics_json,{})};}
async function saveWeekPlan({userId,weekStart,weekEnd,schedule,days,hoursPerDay,metrics={},replace=false}){const versionedMetrics={...metrics,algorithmVersion:PLAN_ALGORITHM_VERSION};const sql=replace?`INSERT INTO study_week_plans(user_id,week_start,week_end,status,schedule_json,config_json,metrics_json,generated_at) VALUES($1,$2,$3,'active',$4::jsonb,$5::jsonb,$6::jsonb,CURRENT_TIMESTAMP) ON CONFLICT(user_id,week_start) DO UPDATE SET week_end=EXCLUDED.week_end,status='active',schedule_json=EXCLUDED.schedule_json,config_json=EXCLUDED.config_json,metrics_json=EXCLUDED.metrics_json,generated_at=CURRENT_TIMESTAMP,completed_at=NULL RETURNING *`:`INSERT INTO study_week_plans(user_id,week_start,week_end,status,schedule_json,config_json,metrics_json) VALUES($1,$2,$3,'active',$4::jsonb,$5::jsonb,$6::jsonb) ON CONFLICT(user_id,week_start) DO NOTHING RETURNING *`;return db.one(sql,[userId,weekStart,weekEnd,JSON.stringify(schedule),JSON.stringify({days,hoursPerDay}),JSON.stringify(versionedMetrics)]);}
function isLegacyPlan(plan){if(!plan)return false;if(plan.metrics?.algorithmVersion!==PLAN_ALGORITHM_VERSION)return true;const blocks=plan.schedule?.blocks||[];return blocks.some(block=>Number(block.minutes)!==180||Number(block.studyMinutes||0)!==120||Number(block.questionMinutes||0)!==60);}
async function getOrCreateCurrentWeek({userId,targets,editalTopics,days,hoursPerDay,adaptiveSignals}){const bounds=getWeekBounds(0);let plan=await getWeekPlan(userId,bounds.weekStart);const hadPlan=!!plan;if(plan&&!isLegacyPlan(plan))return{plan,created:false,migrated:false};const schedule=buildWeeklySchedule({targets,editalTopics,days,hoursPerDay,adaptiveSignals});await saveWeekPlan({userId,...bounds,schedule,days,hoursPerDay,metrics:{generatedFrom:hadPlan?'legacy-snapshot-migration':'initial-or-first-access'},replace:hadPlan});plan=await getWeekPlan(userId,bounds.weekStart);return{plan,created:!hadPlan,migrated:hadPlan};}
async function generateNextWeek({userId,targets,editalTopics,days,hoursPerDay,adaptiveSignals,metrics={}}){const bounds=getWeekBounds(1),currentBounds=getWeekBounds(0),currentPlan=await getWeekPlan(userId,currentBounds.weekStart),rotationTopics=(currentPlan?.schedule?.blocks||[]).map(block=>({discipline:block.discipline,topic:block.topic}));const schedule=buildWeeklySchedule({targets,editalTopics,days,hoursPerDay,adaptiveSignals,rotationTopics});await saveWeekPlan({userId,...bounds,schedule,days,hoursPerDay,metrics:{...metrics,generatedFrom:'completed-previous-week',rotatedFromPreviousWeek:true},replace:true});return getWeekPlan(userId,bounds.weekStart);}
async function markCurrentWeekCompleted(userId){const bounds=getWeekBounds(0);return db.one(`UPDATE study_week_plans SET status='completed',completed_at=CURRENT_TIMESTAMP WHERE user_id=$1 AND week_start=$2::date RETURNING *`,[userId,bounds.weekStart]);}
async function getWeekCompletion(userId,weekStart,weekEnd){const row=await db.one(`SELECT COUNT(*)::int planned,COUNT(*) FILTER(WHERE completed)::int done FROM study_checklist_entries WHERE user_id=$1 AND study_date BETWEEN $2::date AND $3::date`,[userId,weekStart,weekEnd]);const planned=Number(row?.planned||0),done=Number(row?.done||0);return{planned,done,percent:planned?Math.round(done/planned*100):0,complete:planned>0&&done===planned};}
module.exports={PLAN_ALGORITHM_VERSION,getWeekBounds,dateMapForWeek,getWeekPlan,getOrCreateCurrentWeek,generateNextWeek,markCurrentWeekCompleted,getWeekCompletion,saoPauloNow,isoDate};
