const db=require('../db/db');
const {buildWeeklySchedule,DAY_LABELS}=require('./scheduleEngine');
function saoPauloNow(){return new Date(new Date().toLocaleString('en-US',{timeZone:'America/Sao_Paulo'}));}
function isoDate(date){return date.toISOString().slice(0,10);}
function getWeekBounds(offsetWeeks=0){const now=saoPauloNow();const jsDay=now.getDay();const monday=new Date(now);monday.setHours(12,0,0,0);monday.setDate(now.getDate()-((jsDay+6)%7)+(offsetWeeks*7));const sunday=new Date(monday);sunday.setDate(monday.getDate()+6);return{weekStart:isoDate(monday),weekEnd:isoDate(sunday)};}
function dateMapForWeek(weekStart){const monday=new Date(`${weekStart}T12:00:00`);const map={};Object.keys(DAY_LABELS).forEach((key,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);map[key]=isoDate(d);});return map;}
function parseJson(value,fallback){if(!value)return fallback;if(typeof value==='object')return value;try{return JSON.parse(value)}catch{return fallback}}
async function getWeekPlan(userId,weekStart){const row=await db.one('SELECT * FROM study_week_plans WHERE user_id=$1 AND week_start=$2::date',[userId,weekStart]);if(!row)return null;return{...row,schedule:parseJson(row.schedule_json,{}),config:parseJson(row.config_json,{}),metrics:parseJson(row.metrics_json,{})};}
async function saveWeekPlan({userId,weekStart,weekEnd,schedule,days,hoursPerDay,metrics={},replace=false}){const sql=replace?`INSERT INTO study_week_plans(user_id,week_start,week_end,status,schedule_json,config_json,metrics_json,generated_at) VALUES($1,$2,$3,'active',$4::jsonb,$5::jsonb,$6::jsonb,CURRENT_TIMESTAMP) ON CONFLICT(user_id,week_start) DO UPDATE SET week_end=EXCLUDED.week_end,status='active',schedule_json=EXCLUDED.schedule_json,config_json=EXCLUDED.config_json,metrics_json=EXCLUDED.metrics_json,generated_at=CURRENT_TIMESTAMP,completed_at=NULL RETURNING *`:`INSERT INTO study_week_plans(user_id,week_start,week_end,status,schedule_json,config_json,metrics_json) VALUES($1,$2,$3,'active',$4::jsonb,$5::jsonb,$6::jsonb) ON CONFLICT(user_id,week_start) DO NOTHING RETURNING *`;
  return db.one(sql,[userId,weekStart,weekEnd,JSON.stringify(schedule),JSON.stringify({days,hoursPerDay}),JSON.stringify(metrics)]);
}
async function getOrCreateCurrentWeek({userId,targets,editalTopics,days,hoursPerDay,adaptiveSignals}){const bounds=getWeekBounds(0);let plan=await getWeekPlan(userId,bounds.weekStart);if(plan)return{plan,created:false};const schedule=buildWeeklySchedule({targets,editalTopics,days,hoursPerDay,adaptiveSignals});await saveWeekPlan({userId,...bounds,schedule,days,hoursPerDay,metrics:{generatedFrom:'initial-or-first-access'}});plan=await getWeekPlan(userId,bounds.weekStart);return{plan,created:true};}
async function generateNextWeek({userId,targets,editalTopics,days,hoursPerDay,adaptiveSignals,metrics={}}){const bounds=getWeekBounds(1);const schedule=buildWeeklySchedule({targets,editalTopics,days,hoursPerDay,adaptiveSignals});await saveWeekPlan({userId,...bounds,schedule,days,hoursPerDay,metrics:{...metrics,generatedFrom:'completed-previous-week'},replace:true});return getWeekPlan(userId,bounds.weekStart);}
async function markCurrentWeekCompleted(userId){const bounds=getWeekBounds(0);return db.one(`UPDATE study_week_plans SET status='completed',completed_at=CURRENT_TIMESTAMP WHERE user_id=$1 AND week_start=$2::date RETURNING *`,[userId,bounds.weekStart]);}
async function getWeekCompletion(userId,weekStart,weekEnd){const row=await db.one(`SELECT COUNT(*)::int planned,COUNT(*) FILTER(WHERE completed)::int done FROM study_checklist_entries WHERE user_id=$1 AND study_date BETWEEN $2::date AND $3::date`,[userId,weekStart,weekEnd]);const planned=Number(row?.planned||0),done=Number(row?.done||0);return{planned,done,percent:planned?Math.round(done/planned*100):0,complete:planned>0&&done===planned};}
module.exports={getWeekBounds,dateMapForWeek,getWeekPlan,getOrCreateCurrentWeek,generateNextWeek,markCurrentWeekCompleted,getWeekCompletion,saoPauloNow,isoDate};